### ISSUE TITLE
Combine Light and Dark Themes

### ISSUE THREAD

**Issue by sebasptsch** [JuanMTech/google_light_theme#12]
Hi there, just wondering if it's possible to combine these themes into a single theme to use in the HA mobile app so that the system theme preference syncs with HA?

**Comment by JuanMTech** [comment]
Not that I know at the moment. However, you can set up the theme for Light and Dark mode by going to **Developer Tools** and **Services**. Under `Service`, select the option `Home Assistant Frontend: Set theme`. Then, select the name for the theme and the mode that you would like to set up. Then do the same for the other mode.

**Comment by dieugab** [comment]
@sebasptsch it is possible, you can manually edit the theme if you really want it. It uses the following strucure:

```
Theme name:
  modes:
    light:
      primary-color: rgb(0, 122, 253)
      light-primary-color: var(--primary-color)
      ...
    dark:
      primary-color: rgb(10, 131, 254)
      light-primary-color: var(--primary-color)
      ...
```

You can see an example here, which is a forked combination based on the Google Light and Google Dark themes @JuanMTech created: https://github.com/gvssr/home-assistant-config/blob/main/themes/homeOS_theme/homeOS_theme.yaml

You can also define global colors when noted outside the "modes" indentation but I personally don't use that so have no reference for it.
