### ISSUE TITLE
MySQL DB error

### ISSUE THREAD

**Issue by FuzzyMistborn** [JuanMTech/google_light_theme#2]
Getting this error whenever the theme swaps between this one and the dark theme.

```
Error executing query: (MySQLdb._exceptions.DataError) (1406, "Data too long for column 'event_data' at row 1")
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s)]
[parameters: ('themes_updated', '{"themes": {"clear-dark": {"lovelace-background": "center / cover no-repeat url(data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAYABgAAD/4QBmRXhpZgAATU0AKg ... (258882 characters truncated) ...  "#353840", "text-primary-color": "var(--primary-text-color)", "toggle-button-color": "var(--primary-color)"}}, "default_theme": "Google Dark Theme"}', 'LOCAL', datetime.datetime(2020, 1, 20, 22, 12, 0, 22754, tzinfo=<UTC>), datetime.datetime(2020, 1, 20, 22, 12, 0, 79301), '5aced5e890514407ba8d1211aab837d0', None)]
(Background on this error at: http://sqlalche.me/e/9h9h)
```

**Comment by JuanMTech** [comment]
This is the automation that I use and works with no problem:
````
alias: 'Auto day and night theme'
trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: sun.sun
    to: above_horizon
  - platform: state
    entity_id: sun.sun
    to: below_horizon
action:
  - service_template: frontend.set_theme
    data_template:
      name: >
        {% if states.sun.sun.state == "above_horizon" %}
          Google Light Theme
        {% else %}
          Google Dark Theme
        {% endif %}
````
If you are using a different automation, please share it here.

**Comment by FuzzyMistborn** [comment]
I do mine in Node Red but use the same "frontend.set_theme" service.


> [{"id":"70435b9d.050fd4","type":"schedex","z":"1fe83a7f.e0f0b6","name":"Theme Switch","suspended":false,"lat":"40.221012","lon":"-77.029807","ontime":"sunset","ontopic":"","onpayload":"Google Dark Theme","onoffset":"","onrandomoffset":false,"offtime":"sunrise","offtopic":"","offpayload":"Google Light Theme","offoffset":0,"offrandomoffset":0,"mon":true,"tue":true,"wed":true,"thu":true,"fri":true,"sat":true,"sun":true,"x":340,"y":360,"wires":[["436d8534.b41acc"]]},{"id":"436d8534.b41acc","type":"api-call-service","z":"1fe83a7f.e0f0b6","name":"Set Theme","server":"63517380.eb951c","version":1,"debugenabled":false,"service_domain":"frontend","service":"set_theme","entityId":"","data":"{ \"name\": \"{{payload}}\" }","dataType":"json","mergecontext":"","output_location":"","output_location_type":"none","mustacheAltTags":false,"x":530,"y":360,"wires":[[]]},{"id":"63517380.eb951c","type":"server","z":"","name":"Home Assistant","legacy":false,"hassio":false,"rejectUnauthorizedCerts":false,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true}]

**Comment by FuzzyMistborn** [comment]
I get this even when using the service tab in HASS.  I don't have anything other than the theme loaded (don't use custom header).

**Comment by JuanMTech** [comment]
If you are still having issues, here is how I have my automation set up:

````
- id: #'123456789(this is a unique number)'
  alias: Auto Theme Selector
  description: Automatically changes theme depending on the time of day
  trigger:
  - event: start
    platform: homeassistant
  - entity_id: sun.sun
    from: below_horizon
    platform: state
    to: above_horizon
  - entity_id: sun.sun
    from: above_horizon
    platform: state
    to: below_horizon
  condition: []
  action:
  - data_template:
      name: "{% if states.sun.sun.state == \"above_horizon\" %}\n  Google Light Theme\n\
        {% else %}\n  Google Dark Theme\n{% endif %}\n"
    service_template: frontend.set_theme
````
